# -*- coding: utf-8 -*-
"""Python1-print-var-input.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nONUGaaOWpChoAQLpub-gD0gH0XBk6BS

# Python Basic-1
- mengenal fungsi print();
- tanda kurung buka;
- tanda kutip;
- kalimat 1 baris: Hello, World!;
- fungsi beberapa tanda kutip lain;
- tanda kurung tutup.
"""

print("Hello World!@#!#!$")
print("test")

"""#### Latihan: The print() function

- Cetak kalimat "Hello, Python!"
- Cetak nama pertamamu
- Cetak nama pertamamu tanpa petik
- apakah ada bedanya double quote "" dan single quote '?
"""

print("Hello, Python!")
print("Abu")
print('Abu')

"""## Formatting dengan Special Character
`\' = karakter spesial "escaping nature"

`\n` = untuk enter

`\` = escaping karakter

```python
print() = berarti line kosong
```

Tidak boleh ada 2 perintah dalam 1 baris
```python
print("nama depan") print ("nama belakang")
```
"""

print()

print("Saya sudah sarapan tadi pagi\n dan nanti siang makan lagi")
print("Saya sudah sarapan tadi pagi\t dan nanti siang makan lagi")

print("nama saya \"abu\"")

print("\"")

print("satu.","dua.","tiga.")

print("Nama saya","Abu", end=" ")
print("Salam")

print("satu","dua","tiga", sep=", ")

"""## Latihan: The Print Function

Buatlah Program untuk menghasilkan output:
`Programming***Essentials***in...Python`
"""

#Clue
print("Programming","Essentials","in")
print("Python")

#Programming***Essentials***in...PythonPython

print("Programming","Essentials","in", sep="***", end="...")
print("Python"*2)

"""## Latihan: Formatting the output
Membuat duplikasi pola gambar bintang
"""

#clue

print("    *    "*2)
print("   * *   "*2)
print("  *   *  "*2)
print(" *     * "*2)
print("***   ***"*2)
print("  *   *  "*2)
print("  *   *  "*2)
print("  *****  "*2)

print("    *\n   * *\n  *   *\n *     *\n***   ***\n  *   *\n  *   *\n  *****\n"*2)

"""# Literal
literal merupakan notasi untuk mensimbolkan nilai, dapat berupa string, boolean maupun angka (integer dan float)
"""

print("2"*2)
print(2*2)

print(type("2"))
print(type(2))

"""## Integers vs Floats"""

print(5, "mempunyai tipe", type(5))
print(.5, "mempunyai tipe", type(.5))

"""# Penulisan Float dan Integer
Python versi 3 membolehkan pemisahan digit integer dengan underscore "_"
agar mudah dibaca
```python
print (10_000_000)```

Float dipisahkan dengan .(titik) bukan ,(koma)
cara penulisan float bisa 3 cara

- 4.0
- .4 (terbaca nol koma 4)
- 4. (terbaca 4 koma nol)

> 3e08 berarti $ 3 x 10 ^ 8 $  
3e-08 berarti $ 3 x 10 ^ {-8} $

## String

Buatlah program untuk menghasilkan output `I'm Monty Python`
"""



"""## Booelan
Logika benar salah, 1 bernilai benar (True) dan 0 bernilai salah (False)
"""

print(True)
print(False)

print(4>2)
print(3>4)

"""## None"""

print()

"""## Latihan: Python literals - strings
Buat output seperti ini dalam satu line <br/>
`"I'm"`<br/>
`""learning""`<br/>
`'''Python'''`
"""

print('"I\'m"\n""learning""\n"""Python"""')

print("""
"I'm"
""learning""
\"""Python""\"
""")

"""# Operator

### Operator Aritmetika

| Operator | Arti                                                                                          | Contoh                  |
|----------|--------------------------------------------------------------------------------------------------|--------------------------|
| +        | Penambahan                                                                   | x + y                 |
| -        | Pengurangan                                              | x - y                  |
| *        | Perkalian                                                                            | x * y                    |
| /        | Pembagian                                 | x / y                    |
| %        | Modulo - Sisa Pembagian                                 | x % y (sisa pembagian of x/y) |
| //       | Pembagian dan dibulatkan ke bawah | x // y                   |
| **       | Eksponen - Pangkat                                             | x**y (x pangkat y)  |
"""

print(2 ** 3)
print(2 ** 3.)
print(2. ** 3.)
print(2. ** 3)

print(10 / 3)
print(10 // 3)

print(6 / 3.)
print(6 // 3.)

print(-4 + 4)
print(-4. + 8)

"""### Urutan Operator

| Prioritas| Operator |        |
|----------|----------|--------|
| 1        | +, -     | unary  |
| 2        | **       |        |
| 3        | *,/,//,% |        |
| 4        | +, -     | binary |
"""

2 + 3 *5

print(9 % 6 % 2)
print(9 % 6)
print(3 % 2)

print(2 ** 2 ** 3)
print(2 ** 2)
print(2 ** 8)

print((5 * ((25 % 13)+100) / (2 * 13)) // 2)

"""# Variabel
- Apa itu variabel?
- Bagaimana Aturan Penamaannya?
"""

var = 1
print(var)

"""Tulis rumus ini dalam kode program:<br/> $c=\sqrt{a^2+b^2}$"""

a=2.
b=3.
c=(a**2 + b**2) ** 0.5
print("c = ", c)

"""## Latihan: Variables

<b>Cerita Pendek:</b>

Suatu waktu di kebun apel, Darjo memiliki 3 apel, Darno memiliki 5 apel dan Waginem memiliki 6 Apel. mereka sangat bahagia dan hidup lama. selesai.

Tugas Anda
- buat variabe : `Darjo`, `Darno` dan `Waginem`
- isi nilai sesuai dengan jumlah apel yang mereka miliki
- cetak nama variabel dan jumlah apel setiap variabel dalam 1 baris, pisahkan dengan koma
- buat variabel baru dengan nama `totalApel` yang berisi penjumlahan seluruh apel yang mereka miliki
- coba otak atik code dengan membuat variable baru, diisi dengan nilai lain, dan dihitung dengan operator aritmetik lainnya
"""

Darjo = 2
Darno = 5
Waginem = 6

"""## Latihan: Variables: a simple converter

Mil dan kilometer adalah satuan panjang

1 mil memiliki panjang sekitar 1.61 kilometer, buatlah program konversi di bawah ini
- mil ke kilometer;
- kilometer to mil.
jangan ganti apapun terhadap kode yang sudah ada. tulis kodemu pada tanda ###, kemudian hapus tanda tersebut. Uji kode Anda dengan data yang kami sajikan dalam source code

Kode:
```python
kilometer = 12.25
mil = 7.38

mil_ke_kilometer = ###
kilometer_ke_mil = ###

print(mil, "1 mil adalah", round(miles_to_kilometers, 2), "kilometer")
print(kilometer, "1 kilometer adalah", round(kilometers_to_miles, 2), "mil")
```
"""

kilometer = 12.25
mil = 7.38

miles_to_kilometers = mil * 1.61
kilometers_to_miles = kilometer / 1.61

print(mil, "1 mil adalah", round(miles_to_kilometers, 2), "kilometer")
print(kilometer, "1 kilometer adalah", round(kilometers_to_miles, 2), "mil")

"""## Latihan: Operators and expressions

Skenario
lihatlah kode dalam editor, nilai tersebut termasuk tipe float, letakkan nilai tersebut dalam variabel x, dan print variabel tersebut dalam variabel y. Tugasmu adalah melengkapi kode di bawah ini untk menyelesaikan persamaan di bawah

$3x^3 - 2x^2 + 3x - 1$

Hasil harus disimpan dalam variabel y.
ingat bahwa aljabar klasik sering menghilangkan operator perkalian, kamu harus menggunakannya secara eksplisit. Ingat bagaimana cara mengubah tipe data untuk memastikan bahwa x bertipe float.

usahakan kodemu mudah dibaca, uji kode dengan data yang telah kami berikan.

```python
x =  # hardcode your test data here
x = float(x)
# tulis kodemu disini
print("y =", y)
```

Test Data:
```python
#input
x = 0
x = 1
x = -1

#output
y = -1.0
y = 3.0
y = -9.0
```
"""

var = 2
var = 3
print(var)

"""### Exercise

Apa outputnya?
```python
var = 2
var = 3
print(var)
```

Nama variabel mana yang ilegal?
```python
my_var
m
101
averylongvariablename
m101
m 101
Del
del
```

Apa Outputnya?
```python
a = '1'
b = "1"
print(a + b)
```

Apa outputnya?

```python
a = 6
b = 3
a /= 2 * b
print(a)
```

# Comments
Latihan: mana yang seharusnya menjadi komentar, mana yang tidak
"""

#test
print("Hai...")
#test1
#test2

"""# How to talk to a computer
katakunci `input()`<br/>
hasil dari fungsi `input()` adalah <b>string</b>.<br/>
Tidak bisa langsung dikenakan ke operasi aritmetika
"""

print("Katakan sesuatu...")
sesuatu = input()
print("mmmmm", sesuatu, " Oke")

"""### type casting"""

angka = float(input("Masukan Angka : "))
print("Pangkat duanya adalah ", angka**2)

"""#### Replication
coba membuat cetak bangun datar persegi dengan replication

![image.png](attachment:image.png)
"""

print("+" + 10*"-" + "+")
print(("|" + 10*" " + "|\n") * 5, end="")
print("+" + 10*"-" + "+")

"""## Latihan : Simple input and output
Coba utak atik perintah kode dibawah ini
``` python
# Masukkan nilai a dalam float
# Masukkan nilai b dalam float

# hitung hasil penambahan disini
# hitung hasil pengurangan disini
# hitung hasil perkalian disini
# hitung hasil pembagian disini


print("\nYeahhhh")
```
"""

a = float("0.5")
b = float("0.5")

Hasil1 = (a + b)
Hasil2 = (a - b)
Hasil3 = (a * b)
Hasil4 = (a / b)

print("Hasil penambahan: ", Hasil1)
print("Hasil pengurangan: ",Hasil2)
print("Hasil perkalian: ",Hasil3)
print("Hasil pembagian: ",Hasil4)

"""## Latihan: Operators and expressions
Kerjakan rumus berikut:
<img src="images/modul2_pembagian.PNG" width=200px />

input/output yang diharapkan
```python
x = 1
y = 0.6000000000000001

x = 10
y = 0.09901951266867294
```
"""

print("\"I'm\"\n \"\"learning\"\"\n \"\"\"Python\"\"\"\n")